name: Deploy INUZARU API

on:
  push:
    branches: [ "high-version" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Build de la imagen Docker
        run: docker build -t inuzaru-api .

      - name: Levantar contenedor
        run: |
          docker stop inuzaru-api || true
          docker rm inuzaru-api || true
          
          docker run -d \
            --name inuzaru-api \
            --restart always \
            -p 5000:8080 \
            --network bbdd_default \
            inuzaru-api